<?php
/**
 * @author Azguards Team
 * @copyright Copyright (c) Azguards
 * @package Featured Products for Magento 2
 */

use Magento\Catalog\Block\Product\ListProduct;
use Magento\Catalog\Helper\Output;
use Magento\Catalog\Model\Product;
use Magento\Framework\Escaper;
use Magento\Framework\View\Helper\SecureHtmlRenderer;

?>
<?php
/**
 * Product list template
 *
 * @var $block ListProduct
 * @var Escaper $escaper
 * @var SecureHtmlRenderer $secureRenderer
 */
?>
<?php
$_productCollection = $block->getFeaturedProducts();
/** @var Output $_helper */
$_helper = $block->getData('outputHelper');
?>
<?php
$viewMode = 'grid';
?>
<div class="products wrapper <?= /* @noEscape */
$viewMode ?> products-<?= /* @noEscape */
$viewMode ?>">
    <h2>Featured Products</h2>
    <ol class="products list items product-items">
        <?php /** @var $_product Product */ ?>
        <?php foreach ($_productCollection as $_product): ?>
            <li class="item product product-item">
                <div class="product-item-info"
                     id="product-item-info_<?= /* @noEscape */$_product->getId() ?>"
                     data-container="product-<?= /* @noEscape */$viewMode ?>">
                    <?php // Product Image ?>
                    <a href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>"
                       class="product photo product-item-photo"
                       tabindex="-1">
                        <div class="product-image">
                <span class="product-image-container" style="width:240px;">
                    <span class="product-image-wrapper" style="padding-bottom: 125%;">
                        <img class="product-image-photo"
                             src="<?= /* @noEscape */$_product->getThumbnail()
                                 ? $block->getMediaUrl() . 'catalog/product' . $_product->getThumbnail()
                                 : $block->getProductImageUrl($_product); ?>"
                             max-width="240"
                             max-height="300"
                             alt="Clamber Watch">
                    </span>
                </span>
                        </div>
                    </a>
                    <div class="product details product-item-details">
                        <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>">
                                <?= /* @noEscape */
                                $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                            </a>
                        </strong>
                        <?= /* @noEscape */
                        $block->getProductPrice($_product) ?>
                        <?= $block->getProductDetailsHtml($_product) ?>
                    </div>
                </div>

            </li>
        <?php endforeach; ?>
    </ol>
</div>

